spring.application.name=USManager
spring.datasource.url=jdbc:mysql://localhost:3306/university
spring.datasource.username=asdf        
spring.datasource.password=asdf        
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080